version: '3.1'

services:
  webapp:
    image: ghcr.io/spoon2eric/tvalerts:latest  # Replace with the actual image name and tag
    ports:
      - "5000:5000"
    volumes:
      - ./data:/usr/src/app/data  # This will create a volume for persisting data